# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
# Comment the next line if you don't want to use dynamic frameworks

use_frameworks!

def pods
  pod 'SnapKit', '~> 5.0.0'
  pod 'Alamofire', '~>5.0'
  pod 'lottie-ios'
  pod 'Kingfisher', '~> 6.0'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'Then'
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'
  pod 'GoogleSignIn'
  pod 'KakaoSDKUser'
  pod 'KakaoSDKCommon'
  pod 'KakaoSDKAuth'
end

target 'ChaRo-iOS' do
  pods
end

target 'ChaRo-iOSTests' do
  pods
end
  

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
    # some older pods don't support some architectures, anything over iOS 11 resolves that
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end

