# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

def pods
  pod 'SnapKit', '~> 5.0.0'
  pod 'Alamofire', '~>5.0'
  pod 'lottie-ios'
  pod 'Kingfisher', '~> 6.0'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'Then'
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'
  pod 'GoogleSignIn'
#  pod 'KakaoSDKUser'
#  pod 'KakaoSDKCommon'
#  pod 'KakaoSDKAuth'
#  pod 'KakaoSDKLink'
#  pod 'KakaoSDKTemplate'
#  pod 'RxKakaoSDKShare'
end

target 'ChaRo-iOS' do
  pods
end

target 'ChaRo-iOSTests' do
  pods
end
  
