name: Swift

on:
  push:
    branches: [ develop, feature/* ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        pod install --repo-update --clean-install --project-directory=./
        xcodebuild test -workspace ./Gachisaja-iOS.xcworkspace -scheme Gachisaja-iOSTests -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest'
        xcpretty --test --color
