name: Swift

on:
  push:
    branches: [ develop, feature/* ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        pod install --repo-update --clean-install --project-directory=./ChaRo-iOS
        xcodebuild test -workspace ./ChaRo-iOS/ChaRo-iOS.xcworkspace -scheme Charo-iOSTests -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest'
        xcpretty --test --color

    - uses: 8398a7/action-slack@v3
    - name: Notify in Slack
      with:
        status: custom
        fields: workflow,job,commit,repo,ref,author,took
        custom_payload: |
          {
            attachments: [{
              color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
              text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always() 
