name: Swift

on:
  push:
    branches: [ develop, feature/* ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        pod install --repo-update --clean-install --project-directory=./ChaRo-iOS
        xcodebuild clean test -workspace ./ChaRo-iOS/ChaRo-iOS.xcworkspace -scheme ChaRo-iOS -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest'

    - name: Notify in Slack 
      if: always()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: workflow,job,commit,repo,ref,author,took
        mention: here
        if_mention: failure,cancelled
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
 
